// Description:
//  Timezones
//
// Dependencies:
//  None
//
// Configuration:
//   None
//
// Usage:
// var tz = require('./helpers/tz');
// var timezone = tz.timezones[0];
//
// Author:
//   @clsource © 2016
//
// Based On
// Generated by mk420tz.py - see https://github.com/thedod/global420
//              (version: Fri Dec  7 12:34:30 2012)
//
// Data source: http://timezonedb.com/files/timezonedb.csv.zip
//              (version: Wed Nov 14 05:33:11 2012)

exports.timezones = [
 [
  82800,
  [
   "Azores, Portugal",
   "Cape Verde, CV",
   "Scoresbysund, Greenland"
  ]
 ],
 [
  79200,
  [
   "Araguaina, Brazil",
   "Montevideo, Uruguay",
   "Noronha, Brazil",
   "Sao Paulo, Brazil",
   "South Georgia, South Georgia and the South Sandwich Islands"
  ]
 ],
 [
  75600,
  [
   "Asuncion, Paraguay",
   "Bahia, Brazil",
   "Belem, Brazil",
   "Buenos Aires, Argentina",
   "Campo Grande, Brazil",
   "Catamarca, Argentina",
   "Cayenne, French Guiana",
   "Cordoba, Argentina",
   "Cuiaba, Brazil",
   "Fortaleza, Brazil",
   "Godthab, Greenland",
   "Jujuy, Argentina",
   "La Rioja, Argentina",
   "Maceio, Brazil",
   "Mendoza, Argentina",
   "Miquelon, Saint Pierre and Miquelon",
   "Palmer, Antarctica",
   "Paramaribo, Suriname",
   "Recife, Brazil",
   "Rio Gallegos, Argentina",
   "Rothera, Antarctica",
   "Salta, Argentina",
   "San Juan, Argentina",
   "San Luis, Argentina",
   "Santarem, Brazil",
   "Santiago, Chile",
   "Stanley, Falkland Islands",
   "Tucuman, Argentina",
   "Ushuaia, Argentina"
  ]
 ],
 [
  72000,
  [
   "Anguilla, AI",
   "Antigua, Antigua and Barbuda",
   "Aruba, AW",
   "Barbados, BB",
   "Bermuda, BM",
   "Blanc-Sablon, Canada",
   "Boa Vista, Brazil",
   "Curacao, Cura\u00e7ao",
   "Dominica, DM",
   "Eirunepe, Brazil",
   "Glace Bay, Canada",
   "Goose Bay, Canada",
   "Grenada, GD",
   "Guadeloupe, GP",
   "Guyana, GY",
   "Halifax, Canada",
   "Kralendijk, Bonaire, Saint Eustatius and Saba ",
   "La Paz, Bolivia",
   "Lower Princes, Sint Maarten",
   "Manaus, Brazil",
   "Marigot, Saint Martin",
   "Martinique, MQ",
   "Moncton, Canada",
   "Montserrat, MS",
   "Port of Spain, Trinidad and Tobago",
   "Porto Velho, Brazil",
   "Puerto Rico, PR",
   "Rio Branco, Brazil",
   "Santo Domingo, Dominican Republic",
   "St Barthelemy, Saint Barth\u00e9lemy",
   "St Kitts, Saint Kitts and Nevis",
   "St Lucia, Saint Lucia",
   "St Thomas, U.S. Virgin Islands",
   "St Vincent, Saint Vincent and the Grenadines",
   "Thule, Greenland",
   "Tortola, British Virgin Islands"
  ]
 ],
 [
  68400,
  [
   "Atikokan, Canada",
   "Bogota, Colombia",
   "Cayman, Cayman Islands",
   "Detroit, United States",
   "Easter, Chile",
   "Grand Turk, Turks and Caicos Islands",
   "Guayaquil, Ecuador",
   "Havana, Cuba",
   "Indianapolis, Indiana",
   "Iqaluit, Canada",
   "Jamaica, JM",
   "Lima, Peru",
   "Louisville, Kentucky",
   "Marengo, Indiana",
   "Monticello, Kentucky",
   "Montreal, Canada",
   "Nassau, Bahamas",
   "New York, United States",
   "Nipigon, Canada",
   "Panama, PA",
   "Pangnirtung, Canada",
   "Petersburg, Indiana",
   "Port-au-Prince, Haiti",
   "Thunder Bay, Canada",
   "Toronto, Canada",
   "Vevay, Indiana",
   "Vincennes, Indiana",
   "Winamac, Indiana"
  ]
 ],
 [
  64800,
  [
   "Bahia Banderas, Mexico",
   "Belize, BZ",
   "Beulah, North Dakota",
   "Cancun, Mexico",
   "Center, North Dakota",
   "Chicago, United States",
   "Costa Rica, CR",
   "El Salvador, SV",
   "Galapagos, Ecuador",
   "Guatemala, GT",
   "Knox, Indiana",
   "Managua, Nicaragua",
   "Matamoros, Mexico",
   "Menominee, United States",
   "Merida, Mexico",
   "Mexico City, Mexico",
   "Monterrey, Mexico",
   "New Salem, North Dakota",
   "Rainy River, Canada",
   "Rankin Inlet, Canada",
   "Regina, Canada",
   "Resolute, Canada",
   "Swift Current, Canada",
   "Tegucigalpa, Honduras",
   "Tell City, Indiana",
   "Winnipeg, Canada"
  ]
 ],
 [
  61200,
  [
   "Boise, United States",
   "Cambridge Bay, Canada",
   "Chihuahua, Mexico",
   "Creston, Canada",
   "Dawson Creek, Canada",
   "Denver, United States",
   "Edmonton, Canada",
   "Hermosillo, Mexico",
   "Inuvik, Canada",
   "Mazatlan, Mexico",
   "Ojinaga, Mexico",
   "Phoenix, United States",
   "Shiprock, United States",
   "Yellowknife, Canada"
  ]
 ],
 [
  57600,
  [
   "Dawson, Canada",
   "Los Angeles, United States",
   "Metlakatla, United States",
   "Pitcairn, PN",
   "Santa Isabel, Mexico",
   "Tijuana, Mexico",
   "Vancouver, Canada",
   "Whitehorse, Canada"
  ]
 ],
 [
  54000,
  [
   "Anchorage, United States",
   "Juneau, United States",
   "Nome, United States",
   "Sitka, United States",
   "Yakutat, United States"
  ]
 ],
 [
  50400,
  [
   "Adak, United States",
   "Apia, Samoa",
   "Honolulu, United States",
   "Johnston, United States Minor Outlying Islands",
   "Kiritimati, Kiribati",
   "Rarotonga, Cook Islands",
   "Tahiti, French Polynesia"
  ]
 ],
 [
  46800,
  [
   "Auckland, New Zealand",
   "Enderbury, Kiribati",
   "Fakaofo, Tokelau",
   "Fiji, FJ",
   "McMurdo, Antarctica",
   "Midway, United States Minor Outlying Islands",
   "Niue, NU",
   "Pago Pago, American Samoa",
   "South Pole, Antarctica",
   "Tongatapu, Tonga"
  ]
 ],
 [
  43200,
  [
   "Anadyr, Russia",
   "Funafuti, Tuvalu",
   "Kamchatka, Russia",
   "Kwajalein, Marshall Islands",
   "Magadan, Russia",
   "Majuro, Marshall Islands",
   "Nauru, NR",
   "Tarawa, Kiribati",
   "Wake, United States Minor Outlying Islands",
   "Wallis, Wallis and Futuna"
  ]
 ],
 [
  39600,
  [
   "Currie, Australia",
   "Efate, Vanuatu",
   "Guadalcanal, Solomon Islands",
   "Hobart, Australia",
   "Kosrae, Micronesia",
   "Lord Howe, Australia",
   "Macquarie, Antarctica",
   "Melbourne, Australia",
   "Noumea, New Caledonia",
   "Pohnpei, Micronesia",
   "Sakhalin, Russia",
   "Sydney, Australia",
   "Vladivostok, Russia"
  ]
 ],
 [
  36000,
  [
   "Brisbane, Australia",
   "Chuuk, Micronesia",
   "DumontDUrville, Antarctica",
   "Guam, GU",
   "Lindeman, Australia",
   "Port Moresby, Papua New Guinea",
   "Saipan, Northern Mariana Islands",
   "Yakutsk, Russia"
  ]
 ],
 [
  32400,
  [
   "Dili, East Timor",
   "Irkutsk, Russia",
   "Jayapura, Indonesia",
   "Palau, PW",
   "Pyongyang, North Korea",
   "Seoul, South Korea",
   "Tokyo, Japan"
  ]
 ],
 [
  28800,
  [
   "Brunei, BN",
   "Casey, Antarctica",
   "Choibalsan, Mongolia",
   "Chongqing, China",
   "Harbin, China",
   "Hong Kong, HK",
   "Kashgar, China",
   "Krasnoyarsk, Russia",
   "Kuala Lumpur, Malaysia",
   "Kuching, Malaysia",
   "Macau, Macao",
   "Makassar, Indonesia",
   "Manila, Philippines",
   "Perth, Australia",
   "Shanghai, China",
   "Singapore, SG",
   "Taipei, Taiwan",
   "Ulaanbaatar, Mongolia",
   "Urumqi, China"
  ]
 ],
 [
  25200,
  [
   "Bangkok, Thailand",
   "Christmas, Christmas Island",
   "Davis, Antarctica",
   "Dhaka, Bangladesh",
   "Ho Chi Minh, Vietnam",
   "Hovd, Mongolia",
   "Jakarta, Indonesia",
   "Novokuznetsk, Russia",
   "Novosibirsk, Russia",
   "Omsk, Russia",
   "Phnom Penh, Cambodia",
   "Pontianak, Indonesia",
   "Vientiane, Laos"
  ]
 ],
 [
  21600,
  [
   "Almaty, Kazakhstan",
   "Bishkek, Kyrgyzstan",
   "Chagos, British Indian Ocean Territory",
   "Qyzylorda, Kazakhstan",
   "Thimphu, Bhutan",
   "Vostok, Antarctica",
   "Yekaterinburg, Russia"
  ]
 ],
 [
  18000,
  [
   "Aqtau, Kazakhstan",
   "Aqtobe, Kazakhstan",
   "Ashgabat, Turkmenistan",
   "Dushanbe, Tajikistan",
   "Karachi, Pakistan",
   "Kerguelen, French Southern Territories",
   "Maldives, MV",
   "Mawson, Antarctica",
   "Oral, Kazakhstan",
   "Samarkand, Uzbekistan",
   "Tashkent, Uzbekistan"
  ]
 ],
 [
  14400,
  [
   "Baku, Azerbaijan",
   "Dubai, United Arab Emirates",
   "Mahe, Seychelles",
   "Mauritius, MU",
   "Moscow, Russia",
   "Muscat, Oman",
   "Reunion, RE",
   "Samara, Russia",
   "Tbilisi, Georgia",
   "Volgograd, Russia",
   "Yerevan, Armenia"
  ]
 ],
 [
  10800,
  [
   "Addis Ababa, Ethiopia",
   "Amman, Jordan",
   "Antananarivo, Madagascar",
   "Asmara, Eritrea",
   "Baghdad, Iraq",
   "Bahrain, BH",
   "Comoro, Comoros",
   "Dar es Salaam, Tanzania",
   "Djibouti, DJ",
   "Juba, South Sudan",
   "Kaliningrad, Russia",
   "Kampala, Uganda",
   "Khartoum, Sudan",
   "Kuwait, KW",
   "Minsk, Belarus",
   "Mogadishu, Somalia",
   "Nairobi, Kenya",
   "Qatar, QA",
   "Riyadh, Saudi Arabia",
   "Syowa, Antarctica"
  ]
 ],
 [
  7200,
  [
   "Athens, Greece",
   "Beirut, Lebanon",
   "Blantyre, Malawi",
   "Bucharest, Romania",
   "Bujumbura, Burundi",
   "Cairo, Egypt",
   "Chisinau, Moldova",
   "Damascus, Syria",
   "Gaborone, Botswana",
   "Gaza, Palestinian Territory",
   "Harare, Zimbabwe",
   "Hebron, Palestinian Territory",
   "Helsinki, Finland",
   "Istanbul, Turkey",
   "Jerusalem, Israel",
   "Johannesburg, South Africa",
   "Kiev, Ukraine",
   "Lubumbashi, Democratic Republic of the Congo",
   "Lusaka, Zambia",
   "Maputo, Mozambique",
   "Mariehamn, Aland Islands",
   "Maseru, Lesotho",
   "Mbabane, Swaziland",
   "Nicosia, Cyprus",
   "Riga, Latvia",
   "Simferopol, Ukraine",
   "Sofia, Bulgaria",
   "Tallinn, Estonia",
   "Uzhgorod, Ukraine",
   "Vilnius, Lithuania",
   "Windhoek, Namibia",
   "Zaporozhye, Ukraine"
  ]
 ],
 [
  3600,
  [
   "Algiers, Algeria",
   "Amsterdam, Netherlands",
   "Andorra, AD",
   "Bangui, Central African Republic",
   "Belgrade, Serbia",
   "Berlin, Germany",
   "Bratislava, Slovakia",
   "Brazzaville, Republic of the Congo",
   "Brussels, Belgium",
   "Budapest, Hungary",
   "Ceuta, Spain",
   "Copenhagen, Denmark",
   "Douala, Cameroon",
   "Gibraltar, GI",
   "Kinshasa, Democratic Republic of the Congo",
   "Lagos, Nigeria",
   "Libreville, Gabon",
   "Ljubljana, Slovenia",
   "Longyearbyen, Svalbard and Jan Mayen",
   "Luanda, Angola",
   "Luxembourg, LU",
   "Madrid, Spain",
   "Malabo, Equatorial Guinea",
   "Malta, MT",
   "Monaco, MC",
   "Ndjamena, Chad",
   "Niamey, Niger",
   "Oslo, Norway",
   "Paris, France",
   "Podgorica, Montenegro",
   "Porto-Novo, Benin",
   "Prague, Czech Republic",
   "Rome, Italy",
   "San Marino, SM",
   "Sarajevo, Bosnia and Herzegovina",
   "Skopje, Macedonia",
   "Stockholm, Sweden",
   "Tirane, Albania",
   "Tripoli, Libya",
   "Tunis, Tunisia",
   "Vaduz, Liechtenstein",
   "Vatican, VA",
   "Vienna, Austria",
   "Warsaw, Poland",
   "Zagreb, Croatia",
   "Zurich, Switzerland"
  ]
 ],
 [
  0,
  [
   "Abidjan, Ivory Coast",
   "Accra, Ghana",
   "Bamako, Mali",
   "Banjul, Gambia",
   "Bissau, Guinea-Bissau",
   "Canary, Spain",
   "Casablanca, Morocco",
   "Conakry, Guinea",
   "Dakar, Senegal",
   "Danmarkshavn, Greenland",
   "Dublin, Ireland",
   "El Aaiun, Western Sahara",
   "Faroe, Faroe Islands",
   "Freetown, Sierra Leone",
   "Guernsey, GG",
   "Isle of Man, IM",
   "Jersey, JE",
   "Lisbon, Portugal",
   "Lome, Togo",
   "London, United Kingdom",
   "Madeira, Portugal",
   "Monrovia, Liberia",
   "Nouakchott, Mauritania",
   "Ouagadougou, Burkina Faso",
   "Reykjavik, Iceland",
   "Sao Tome, Sao Tome and Principe",
   "St Helena, Saint Helena"
  ]
 ]
];
